sudo: required
services: docker
language: bash
env:
    global:
      - QEMU_VER=v2.9.1
      - DOCKER_REPO=innovate/docs
    matrix:
      - ARCH=amd64  QEMU_ARCH=x86_64
      - ARCH=armhf  QEMU_ARCH=arm    
      - ARCH=arm64  QEMU_ARCH=aarch64

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo apt-get -y install qemu qemu-user-static qemu-user binfmt-support httpie
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - docker build -t $DOCKER_REPO:$ARCH-latest --build-arg ARCH=${ARCH} ./

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push $DOCKER_REPO:$ARCH-latest ; fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker tag $DOCKER_REPO:$ARCH-latest $DOCKER_REPO:$ARCH-$TRAVIS_COMMIT; docker push $DOCKER_REPO:$ARCH-$TRAVIS_COMMIT ; fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$ARCH" == "arm64" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then http --verify no PUT "https://docs-controller.innovatete.ch/deployment/$TRAVIS_COMMIT" Authorization:"Bearer $HELMET_TOKEN" ; fi
  